<?php

namespace Tests\Feature;

use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Modules\Hr\App\Models\Allowance;
use Tests\TestCase;

class AllowanceTest extends TestCase
{
	protected function setUp(): void
	{
		parent::setUp(); // TODO: Change the autogenerated stub
	}


	/**
     * A basic feature test example.
     */
	public function test_example(): void
	{
		$response = $this->post('/login', [
			'email' => 'admin@n.com',
			'password' => '123456789',
		]);

		$this->assertAuthenticated();
		$response = $this->get('/allowance');

		$response->assertStatus(200);
	}

	public function test_create_allowance()
	{
		$response = $this->post('/login', [
			'email' => 'admin@n.com',
			'password' => '123456789',
		]);
		$this->assertAuthenticated();
		$this->post('/allowance', [
			'is_active' => true,
			'branch_id' => 1,
			'en' => [
				'name' => 'job title test'
			],
			'ar' => [
				'name' => 'هنا اول تست كاس '
			]
		]);
		$response = $this->get('/allowance');
		$response->assertStatus(200);
	}

	public function test_update_allowance()
	{

		$user = User::whereEmail('admin@n.com')->first();
		$this->actingAs($user);
		$allowance = Allowance::latest()->first();
//		dd($job_title) ;
		$response = $this->withSession(['_token' => csrf_token()])
			->withHeaders([
				'X-Inertia' => true,
				'X-Requested-With' => 'XMLHttpRequest',
			])
			->put("allowance/{$allowance->id}", [
				'is_active' => false,
				'branch_id' => 1,
				'en' => [
					'name' => 'هنا اول تست كاس '
				],
				'ar' => [
					'name' => 'هنا اول تست كاس '
				]

			]);
		$response->assertStatus(303);
	}

	public function test_job_delete()
	{

		$user = User::whereEmail('admin@n.com')->first();
		$this->actingAs($user);
		$allowance = Allowance::latest()->first();
		$response = $this
//			->withSession(['_token' => csrf_token()])
			->withHeaders([
				'X-Inertia' => true,
				'X-Requested-With' => 'XMLHttpRequest',
			])
			->delete("allowance/{$allowance->id}");
		$response->assertStatus(303);
	}
}
